CREATE TABLE Conto(
    
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    balance REAL
);

CREATE TABLE Utente(
    
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128),
    password VARCHAR(128),
    contoId INTEGER,
    tipo INTEGER,
    FOREIGN KEY (contoId) REFERENCES Conto(id)
);

CREATE TABLE Prodotto(

    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(128),
    description VARCHAR(128),
    price REAL,
    quantity INTEGER,
    imgUrl VARCHAR(128),
    venditoreId INTEGER,
    FOREIGN KEY (venditoreId) REFERENCES Utente(id)
);

INSERT INTO Conto(id, balance)
VALUES(default, 130.00),
      (default, 5.00),
      (default, 57.45),
      (default, 2.54);

INSERT INTO Utente(id, username, password, contoId, tipo)
VALUES(default, 'AndreaGirau', '0', 1, 1),
      (default, 'EfisioGirau', '1', 2, 1),
      (default, 'HarryPotter', '2', 3, 2),
      (default, 'TomMarvoloRiddle', '3', 4, 2);

INSERT INTO Prodotto(id, name, description, price, quantity, imgUrl, venditoreId)
VALUES(default, 'Casper(1995)- DVD', '...', 13.99, 18, 'img/Film/casper_dvd.jpg', 2),
      (default, 'Hercules(1996)- DVD', '...', 13.99, 7, 'img/Film/hercules_dvd.jpg', 2),
      (default, 'American Sniper(2015)- Blu-Ray', '...', 18.99, 21, 'img/Film/american_sniper_blu_ray.jpg', 2),
      (default, 'The Imitation Game(2015)- Blu-Ray', '...', 18.99, 9, 'img/Film/the_imitation_game.jpg', 2),
      (default, 'Harry Potter (saga completa)- Blu-Ray', '...', 19.89, 11, 'img/Film/harry_potter_cofanetto.jpg', 2),
      (default, 'Ritorno Al Futuro (La Trilogia)- Blu-Ray', '...', 18.89, 5, 'img/Film/ritorno_al_futuro_trilogia.jpeg', 2),
      (default, '1984 - Orwell', '...', 8.99, 13, 'img/Film/casper_dvd.jpg', 2),
      (default, 'Il Piccolo Principe - Antoine de Saint-Exupéry', '...', 5.99, 26, 'img/Libri/il_piccolo_principe_book.jpeg', 2),
      (default, 'Ventimila Leghe Sotto I Mari - Verne', '...', 6.89, 4, 'img/Libri/ventimila_leghe_sotto_i_mari_book.jpg', 2),
      (default, 'Harry Potter(cofanetto 8 libri)- J.K. Rowling', '...', 54.89, 7, 'img/Libri/harry_potter_cofanetto_books.jpg', 2),
      (default, 'Il Signore Degli Anelli(trilogia)- J.R.R. Tolkien', '...', 13.89, 13, 'img/Libri/il_signore_degli_anelli_trilogia.jpeg', 2),
      (default, 'Collana Doni Della Morte - Harry Potter', '...', 7.50, 15, 'img/Gadgets/collana_doni_della_morte.jpg', 2),
      (default, 'Unico Anello - Il Signore Degli Anelli', '...', 9.99, 23, 'img/Gadgets/unico_signore_degli_anelli.jpg', 2),
      (default, 'Costume Spiderman', '...', 19.89, 6, 'img/Gadgets/spiderman_costume.jpg', 2);
